apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: 51-router
  labels:
    machineconfiguration.openshift.io/role: router
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      files:
      - path: /etc/routertest
        mode: 0644
        contents:
          source: data:,router
