apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0005
spec:
  capacity:
    storage: 20Gi 
  accessModes:
  - ReadWriteOnce
  nfs: 
    path: /home/PV/pv0005
    server: 10.131.1.10
  persistentVolumeReclaimPolicy: Retain 

