apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0002
spec:
  capacity:
    storage: 20Gi 
  accessModes:
  - ReadWriteOnce
  nfs: 
    path: /PV/pv0002
    server: 10.131.2.10
  persistentVolumeReclaimPolicy: Retain 

