apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
spec:
  capacity:
    storage: 20Gi 
  accessModes:
  - ReadWriteOnce
  nfs: 
    path: /PV/pv0001
    server: 10.131.2.10
  persistentVolumeReclaimPolicy: Retain 

