apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0008
spec:
  capacity:
    storage: 5Gi 
  accessModes:
  - ReadWriteOnce
  nfs: 
    path: /home/PV/pv0008
    server: 10.131.1.10
  persistentVolumeReclaimPolicy: Retain 

