apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0009
spec:
  capacity:
    storage: 1Gi 
  accessModes:
  - ReadWriteOnce
  nfs: 
    path: /home/PV/pv0009
    server: 10.131.1.10
  persistentVolumeReclaimPolicy: Retain 

