apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry
spec:
  capacity:
    storage: 100G
  accessModes:
  - ReadWriteMany
  nfs: 
    path: /home/PV/registry
    server: 10.131.1.10
  persistentVolumeReclaimPolicy: Retain 

