kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v1alpha2
storageConfig:
  registry:
    imageURL: registry.ocp4.example.io:5000/mirror4/oc-mirror-metadata
    skipTLS: false
mirror:
  platform:
    channels:
    - name: stable-4.12
      type: ocp
  operators:
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.12
    packages:
    - name: servicemeshoperator
      channels:
      - name: stable
    - name: cluster-logging
      channels:
      - name: stable
    - name: elasticsearch-operator
      channels:
      - name: stable
    - name: kiali-ossm
      channels:
      - name: stable
    - name: ocs-operator
      channels: 
      - name: stable-4.12
    - name: odf-operator
      channels:
      - name: stable-4.12
    - name: quay-operator
      channels: 
      - name: stable-3.8
    - name: quay-bridge-operator
      channels:
      - name: stable-3.8
    - name: openshift-pipelines-operator-rh
      channels:
      - name: latest
    - name: ingress-node-firewall
      channels:
      - name: stable
    - name: jaeger-product
      channels:
      - name: stable
    - name: ocs-operator
      channels: 
      - name: stable-4.12
    - name: redhat-oadp-operator
      channels:
      - name: stable-1.1
    - name: security-profiles-operator
      channels: 
      - name: release-alpha-rhel-8
    - name: opentelemetry-product
      channels:
      - name: stable
    - name: local-storage-operator
      channels:
      - name: stable
  additionalImages:
  - name: registry.redhat.io/ubi8/ubi:latest
  helm: {}
